/**
 * Category list must match backend Transaction model enum exactly
 * so budget spending aggregation matches transactions.
 */
export const TRANSACTION_CATEGORIES = [
  "Groceries",
  "Food & Drinks",
  "Coffee & Snacks",
  "Shopping",
  "Personal Care",
  "Health",
  "Pharmacy",
  "Rent",
  "Mortgage",
  "Home Maintenance",
  "Utilities",
  "Internet",
  "Phone Bill",
  "Fuel",
  "Public Transit",
  "Taxi / Ride-sharing",
  "Parking",
  "Vehicle Maintenance",
  "Movies",
  "Music",
  "Games",
  "Activities",
  "Nightlife",
  "Subscriptions",
  "Bank Fees",
  "Investments",
  "Insurance",
  "Loans",
  "Tax Payments",
  "Flights",
  "Hotels",
  "Travel Food",
  "Transportation",
  "Vacation Activities",
  "Salary",
  "Bonus",
  "Refund",
  "Investment Income",
  "Gift Income",
  "Other Income",
  "Transfer In",
  "Transfer Out",
] as const;
